### ISSUE TITLE
Installation on Cypress 12

### ISSUE THREAD

**Issue by InTheZ** [coco1979ka/cypress-websocket-plugin#18]
I ran an npm install on this plugin but can't figure out how to register the plugin with Cypress. When I run the test with websockets it basically says it can't find mockWebSocket. I also added a block like this in cypress.config.js

    setupNodeEvents(on) {
      websocket.install(on);
    },

It would be good to have this in the README.md as well.

**Comment by InTheZ** [comment]
I was able to get it working with

import "cypress-mock-websocket-plugin"

inside the cypress/support/commands.ts file. Is that the correct way to use this plugin?

**Comment by coco1979ka** [comment]
Yes that's correct. I will update the documentation, thanks for your comment 👍

**Comment by InTheZ** [comment]
Happy to start a new issue, but, the 

win.MockedWebSocket = WebSocket

appears to not catch a new Websocket(...). When I copy your code over and switch it to:

win.WebSocket = WebSocket

then it catches it. Is there something I'm missing? I'm not sure how it's supposed to work in your test conditions. It looks like in the Cypress thread that is how an earlier author had his working as well.

**Comment by coco1979ka** [comment]
Are you using the native WebSocket API?

**Comment by InTheZ** [comment]
I'm using a package called: vue-native-websocket-vue3

It uses the native WebSocket API. It wraps in a Vue3 Pinia store to share it across multiple views. When I was debugging it, I implemented it with the native WebSocket API and once I got that to work (it couldn't connect), the package also worked.

**Comment by coco1979ka** [comment]
Ok, I see... Well, as mentioned in the docs, the plugin only works with an implementation that allows to replace the constructor (like rxjs or Apollo client can do). 
Unfortunately, looking at the docs of your package, this does not seem to be possible. I was trying hard to get the plugin working with the native websocket API, but couldn't figure it out. Maybe I'll investigate a little more - also for my tests it would be nice to use the native API instead of rxjs. If you have any ideas, let me know!

**Comment by coco1979ka** [comment]
Please continue the discussion in  #19
